packages:
  - packages/*
  - apps/*
  - tools/*

catalogs:
  react-next:
    '@types/react': ^19.0.8
    '@types/react-dom': ^19.0.3
    prettier: ^3.5.3
    react: ^19.0.0
    react-dom: ^19.0.0
    typescript: ^5.7.2
    vite: 6.3.5
    vitest: ^3.0.5
    eslint: '^9.32.0'
    '@tanstack/react-form': ^1.19.0
    graphql-request: ^7.2.0
    neverthrow: ^8.2.0
    zustand-mutative: ^1.3.0
